--- #YAML:1.0
name:               CPANPLUS-Dist-Gentoo
version:            0.06
abstract:           CPANPLUS backend generating Gentoo ebuilds.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Carp:                 0
    CPANPLUS:             0
    Cwd:                  0
    File::Copy:           0
    File::Path:           0
    File::Spec::Functions:  0
    IPC::Cmd:             0
    perl:                 5.006
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=CPANPLUS-Dist-Gentoo
    homepage:    http://search.cpan.org/dist/CPANPLUS-Dist-Gentoo/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/perl/modules/CPANPLUS-Dist-Gentoo.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
