--- #YAML:1.0
name:               CPANPLUS-Dist-Gentoo
version:            0.03
abstract:           CPANPLUS backend generating Gentoo ebuilds.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPANPLUS:             0
    File::Copy:           0
    File::Path:           0
    File::Spec::Functions:  0
    IPC::Cmd:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
build_requires:
    ExtUtils::MakeMaker:           0
    Test::More:                    0
